### ISSUE TITLE
Home Assistant: Device States

### ISSUE THREAD

**Issue by scottsweb** [scottsweb/ham#29]
Use the device tracker to monitor device states: https://github.com/btotharye/Home-AssistantConfig-1/blob/master/sensor/devices_states.yaml

```
- platform: template
  sensors:
      wii:
        friendly_name: 'Wii'
        value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"
```
